<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ebnf</string>
		<string>txt</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\(\*</string>
	<key>foldingStopMarker</key>
	<string>\*\)</string>
	<key>name</key>
	<string>EBNF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(\b(?:\w|\s|[\-_0-9])+\b)\s*=</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.ebnf.syntax-rule</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#non-terminal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quote-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double-quote-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special-sequence</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>^\(\*</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.ebnf</string>
		</dict>
		<key>double-quote-string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<key>non-terminal</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.ebnf.non-terminal</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w(?:\w|\s|[\-_0-9])*\w)</string>
		</dict>
		<key>single-quote-string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<key>special-sequence</key>
		<dict>
			<key>begin</key>
			<string>\?</string>
			<key>end</key>
			<string>\?</string>
			<key>name</key>
			<string>entity.other.attribute-name</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ebnf</string>
	<key>uuid</key>
	<string>D9954069-097B-4361-818D-EF4986D442E7</string>
</dict>
</plist>
