<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ebnf</string>
		<string>txt</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*\(\*</string>
	<key>foldingStopMarker</key>
	<string>^\s*\*\)</string>
	<key>name</key>
	<string>EBNF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\(\*</string>
			<key>end</key>
			<string>^\*\)</string>
			<key>name</key>
			<string>comment.block.ebnf</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.ebnf.non-terminal</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w(?:\w|\s|[\-_0-9])*\w)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\?</string>
			<key>end</key>
			<string>\?</string>
			<key>name</key>
			<string>entity.other.attribute-name</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ebnf</string>
	<key>uuid</key>
	<string>D9954069-097B-4361-818D-EF4986D442E7</string>
</dict>
</plist>
